name: at-python-template
channels:
  - conda-forge
  - defaults
dependencies:
  # no python version specified here, we use different versions in the CI pipeline
  - pytest>=5.4
  - pytest-mock>=3.3.0
  - cookiecutter~=1.7.3
  - pyhocon=0.3.*
  - PyYAML>=5.3
  - pip
  - pip:
      - typer~=0.4.0
